### PR TITLE
Update: Documentation searchTraces handler, update its type. (BTA-731)

### PR DESCRIPTION
**Pull request by qhello**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/51)

### CODE REVIEW

**Review by conord33 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/51)* status: all files reviewed, 2 unresolved discussions (waiting on @Paturages and @qhello)

___
*[README.md, line 139 at r1](https://reviewable.io/reviews/stratumn/sdk-js/51#-MT1QTql6XPz2nwaRwWq:-MT1QTqm96E7x1jvvJCR:b-tgddjp) ([raw file](https://github.com/stratumn/sdk-js/blob/38bcfa527ee654fcfb4dd6072cca193daba08a69/README.md#L139)):*
> ```Markdown
> - The `data` object argument must be valid against the JSON schema of the form you are using, otherwise Trace will throw a validation error.
> 
> ### Requesting the transfer of ownership of a trace
> ```

can you move all of the ToO stuff to a new "deprecated section of the readme?
___
*[src/types/trace.ts, line 169 at r1](https://reviewable.io/reviews/stratumn/sdk-js/51#-MT1PJsb3gFr8XKn-YW7:-MT1PJsb3gFr8XKn-YW8:b2ni78k) ([raw file](https://github.com/stratumn/sdk-js/blob/d4a6b2c709e6d3398e542ed5d9e1d6753ab3213f/src/types/trace.ts#L169)):*
> ```XML
>  */
> export interface SearchTracesFilter {
>   // TODO
> ```

lol

**Review by Paturages — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/51)* status: all files reviewed, 2 unresolved discussions (waiting on @conord33 and @qhello)

___
*[src/types/trace.ts, line 169 at r1](https://reviewable.io/reviews/stratumn/sdk-js/51#-MT1PJsb3gFr8XKn-YW7:-MT5Px7qEKifPKXMvLU6:b-cjkumv) ([raw file](https://github.com/stratumn/sdk-js/blob/d4a6b2c709e6d3398e542ed5d9e1d6753ab3213f/src/types/trace.ts#L169)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

lol
</blockquote></details>

a rare instance of a TODO comment actually being done

there's likely other use cases that could be included (e.g. search by date) but I guess we only really need searching by tags right now

**Review by conord33 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/51)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @qhello)

___
*[src/types/trace.ts, line 169 at r1](https://reviewable.io/reviews/stratumn/sdk-js/51#-MT1PJsb3gFr8XKn-YW7:-MT5TBUCAR56eJV97SrY:b457zqq) ([raw file](https://github.com/stratumn/sdk-js/blob/d4a6b2c709e6d3398e542ed5d9e1d6753ab3213f/src/types/trace.ts#L169)):*
<details><summary><i>Previously, Paturages (Paturages) wrote…</i></summary><blockquote>

a rare instance of a TODO comment actually being done

there's likely other use cases that could be included (e.g. search by date) but I guess we only really need searching by tags right now
</blockquote></details>

yeah, we will need to address that in a more concerted effort, apparently the js search implementation is much more flexibile than the java one

**Pull request merged**
