### PR TITLE
Upgrade: Bots can now use the SDK (BTA-827)

### PR DESCRIPTION
**Pull request by qhello**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/56)

### CODE REVIEW

**Review by haroldcb — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @conord33 and @Paturages)

**Review by Paturages — APPROVED** [review]
:lgtm:

replacing user IDs by account IDs is scary, let's hope we haven't missed any stray user IDs

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/56#-:-MWczGSUEmRScw0zWZT_:b-ec5d5q)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @conord33)

**Review by conord33 — APPROVED** [review]
:lgtm_strong: yeah hopefully it works! :crossed_fingers: so you tested with a user and bot? ideally we want our clients to just be able to update their private key and have everything work the same. so user private key to bot private key. 

looks like it should work :slightly_smiling_face: 

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/56#-:-MWeN9nL9S0-heKsxq6T:b2rna2w)* status: all files reviewed, 2 unresolved discussions (waiting on @qhello)

___
*[src/graphql.ts, line 134 at r1](https://reviewable.io/reviews/stratumn/sdk-js/56#-MWeNOSt3B5pwv_x9ebE:-MWeNOSt3B5pwv_x9ebF:b-54vfvs) ([raw file](https://github.com/stratumn/sdk-js/blob/b42a8dc81a52486cfaea9ef8057adada1d604717/src/graphql.ts#L134)):*
> ```XML
>   export const document = gql`
>     query configQuery($workflowId: BigInt!) {
>       account: me {
> ```

pretty misleading to use `account` as the variable name for a `user` object... :facepalm: 
___
*[src/types/sdk.ts, line 31 at r1](https://reviewable.io/reviews/stratumn/sdk-js/56#-MWeN1Fq-XnpO5wqV-0s:-MWeN1Fq-XnpO5wqV-0t:blbqnec) ([raw file](https://github.com/stratumn/sdk-js/blob/b42a8dc81a52486cfaea9ef8057adada1d604717/src/types/sdk.ts#L31)):*
> ```XML
>    * The user id
>    */
>   userId: string;
> ```

:wave:

**Pull request merged**
