### PR TITLE
New: Handle bots with multiple groups [BTA-924]

### PR DESCRIPTION
**Pull request by haroldcb**
Not really sure how to test it (how to set up the local env variables), but let me know if you have any feedbacks yet

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/59)

### CODE REVIEW

**Review by conord33 — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/59)* status: all files reviewed, 5 unresolved discussions (waiting on @haroldcb and @qhello)

___
*[src/sdk.ts, line 497 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxmWAs2ENARMYnpsJY:-MYxmWAs2ENARMYnpsJZ:b-1f8gwl) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/sdk.ts#L497)):*
> ```XML
>     const config = await this.getConfig();
>     const { workflowId, accountId, configId } = config;
>     const groupId = config.groupId();
> ```

this should get the groupLabel from the `NewTraceInput` right?
___
*[src/sdk.ts, line 565 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxmbY945zI6vqeDKPP:-MYxmbY945zI6vqeDKPQ:b-c3bwb6) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/sdk.ts#L565)):*
> ```XML
>     const config = await this.getConfig();
>     const { workflowId, accountId, configId } = config;
>     const groupId = config.groupId();
> ```

this should check the input for a gropuLabel
___
*[src/sdkConfig.ts, line 9 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxjB0QAXb8sz5srmsa:-MYxjB0QAXb8sz5srmsb:bawfn1t) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/sdkConfig.ts#L9)):*
> ```XML
>   accountId: string;
>   groupLabel: string | undefined;
>   groupLabelToIdMap: Record<string, string>;
> ```

what is `Record`?
___
*[src/sdkConfig.ts, line 35 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxm3U4AnXxUFezign9:-MYxm3U4AnXxUFezignA:bm6mue6) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/sdkConfig.ts#L35)):*
> ```XML
>   }
> 
>   private getGroupIdByLabel(groupLabelParam: string | null): string {
> ```

you should add a test for this
___
*[src/types/trace.ts, line 133 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxmqC25urLcOZ7OnWF:-MYxmqC25urLcOZ7OnWG:b4yxml8) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/types/trace.ts#L133)):*
> ```XML
>   data?: TLinkData;
>   prevLink?: ITraceLink;
>   groupLabel?: string;
> ```

i think you can leave this one out since its deprecated. i am pretty sure this interface only gets used by deprecated methods.

**Comment by haroldcb** [comment]
___
*[src/sdk.ts, line 497 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxmWAs2ENARMYnpsJY:-MZC3HMt7Fdnb90Gmn8N:b-m0hoyh) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/sdk.ts#L497)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

this should get the groupLabel from the `NewTraceInput` right?
</blockquote></details>

You're right!
Done.

**Comment by haroldcb** [comment]
___
*[src/sdk.ts, line 565 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxmbY945zI6vqeDKPP:-MZC3M2N6YlHjq6KU9OF:bb6un1j) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/sdk.ts#L565)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

this should check the input for a gropuLabel
</blockquote></details>

Done

**Comment by haroldcb** [comment]
___
*[src/sdkConfig.ts, line 9 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxjB0QAXb8sz5srmsa:-MZC5p6H7FDfFJUKG2Pm:b-2q1n6w) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/sdkConfig.ts#L9)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

what is `Record`?
</blockquote></details>

I'm not really used to typescript : https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeystype is it not used ? 
I changed for 
groupLabelToIdMap: { [key: string]: string };

**Review by Paturages — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/59)* status: all files reviewed, 5 unresolved discussions (waiting on @conord33, @haroldcb, and @qhello)

___
*[src/sdkConfig.ts, line 9 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxjB0QAXb8sz5srmsa:-MZC7qiOAqZW3Luo81OE:bde5uj8) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/sdkConfig.ts#L9)):*
<details><summary><i>Previously, haroldcb wrote…</i></summary><blockquote>

I'm not really used to typescript : https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeystype is it not used ? 
I changed for 
groupLabelToIdMap: { [key: string]: string };
</blockquote></details>

they're both equivalent, Record I find is more idiomatic to TypeScript/typed languages and { [key: string]: string } is closer to JavaScript itself

**Comment by haroldcb** [comment]
___
*[src/sdkConfig.ts, line 9 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxjB0QAXb8sz5srmsa:-MZCAkyWCnX3pfVA1dg3:btv84cb) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/sdkConfig.ts#L9)):*
<details><summary><i>Previously, Paturages (Paturages) wrote…</i></summary><blockquote>

they're both equivalent, Record I find is more idiomatic to TypeScript/typed languages and { [key: string]: string } is closer to JavaScript itself
</blockquote></details>

So I can keep Record ?

**Comment by haroldcb** [comment]
___
*[src/sdkConfig.ts, line 35 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxm3U4AnXxUFezign9:-MZCUzVpAWBENWJRRGIY:b-896fix) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/sdkConfig.ts#L35)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

you should add a test for this
</blockquote></details>

Done.

**Comment by haroldcb** [comment]
___
*[src/types/trace.ts, line 133 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxmqC25urLcOZ7OnWF:-MZCV0jHBexzsdxezSwS:b-896fix) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/types/trace.ts#L133)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

i think you can leave this one out since its deprecated. i am pretty sure this interface only gets used by deprecated methods.
</blockquote></details>

Done.

**Comment by haroldcb** [comment]
And about tests, how do I add variables in env files ?

**Review by conord33 — COMMENTED** [review]
this is where the sem env vars get set https://stratumn.semaphoreci.com/secrets/4d3bd2d3-b7ba-4c7c-a8b1-c8c754abff25/edit

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/59#-:-MZCdIFd7Y0ETgaITt9P:b-x1zh4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @qhello)

___
*[src/sdkConfig.ts, line 9 at r1](https://reviewable.io/reviews/stratumn/sdk-js/59#-MYxjB0QAXb8sz5srmsa:-MZCbZvd9hqDDq3GT3s5:br3mcfy) ([raw file](https://github.com/stratumn/sdk-js/blob/23c838daa26465957e9377f91e22f5c3d64298d8/src/sdkConfig.ts#L9)):*
<details><summary><i>Previously, haroldcb wrote…</i></summary><blockquote>

So I can keep Record ? 
</blockquote></details>

yeah record is good, just hadnt seen it before. much better than doing the typed map...

**Review by conord33 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-js/59)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @qhello)

**Pull request merged**
